kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.17
        k8s-1:
          ansible_host: 192.168.1.18
        k8s-2:
          ansible_host: 192.168.1.19
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.1.21
        k8s-4:
          ansible_host: 192.168.1.22
